#!/usr/bin/env python
#
# Copyright (c) 2016 Tim Savannah under LGPLv3. See LICENSE for more information.
# This application marks in the kmsg log the current drift between kernel uptime and clock time. The more often this is done, the more accurate the dates in between will be.
import sys

import printk_timestamp_converter

def printUsage():
    sys.stderr.write("""printk_mark_drift
  Marks the current drift between the kernel's uptime and clock time in kmsg log.

  These marks are used to calculate timestamps adjusting for drift in the timesource. The more often this is done, the more accurate timestamps you can get.
""")


if __name__ == '__main__':
    if '--help' in sys.argv or '-h' in sys.argv or '-?' in sys.argv:
        printUsage()
        sys.exit(0)

    if len(sys.argv) != 1:
        sys.stderr.write('printk_mark_drift takes no arguments.\n\n')
        printUsage()
        sys.exit(1)

    try:
        printk_timestamp_converter.printk_markCurrentDrift()
    except Exception as e:
        sys.stderr.write('Cannot write to /dev/kmsg . Please retry as root or a user that has such permission.\n')
        sys.exit(2)

# vim: sw=4 ts=4 expandtab
